In [51]:
import numpy as np
import time

## Numpy Arrays (narrays)

In [52]:
x = np.array([1, 2, 3, 4])
print(x[0])
print(x[3])
print(x[-1])
print(x[-2])

1
4
4
3


In [53]:
x[0] = 30
x[-1] = 60
print(x)

[30  2  3 60]


In [54]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x)
print(x[0, 1])

x[0, 1] = 20
print(x)
print(x[0, 1])

[[1 2 3 4]
 [5 6 7 8]]
2
[[ 1 20  3  4]
 [ 5  6  7  8]]
20


In [55]:
#delete 
x = np.array([1, 2, 3, 4])
print(x)

x = np.delete(x, [0, 1])
print(x)

x = np.delete(x, 0)
print(x)

[1 2 3 4]
[3 4]
[4]


In [56]:
#axis = 0 = row
#axis = 1 = column

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x)
print("******************")
#delete row
x = np.delete(x, 0, axis=0)
print(x)
print("******************")
#delete column
x = np.delete(x, 0, axis=1)
print(x)

# x = np.delete(x, [0, 1], axis=0)
# print(x)

# x = np.delete(x, [0, 1], axis=1)
# print(x)

[[1 2 3 4]
 [5 6 7 8]]
******************
[[5 6 7 8]]
******************
[[6 7 8]]


In [57]:
#append
x = np.array([1, 2, 3, 4])
print(x)

x = np.append(x, [5, 6])
print(x)

x = np.append(x, [7, 8])
print(x)

[1 2 3 4]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]


In [58]:
#axis = 0 = row
#axis = 1 = column
x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.append(x, [[7, 8, 9]], axis=0)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
#axis = 0 = row
#axis = 1 = column
x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.append(x, [[7], [8]], axis=1)
print(x)

[[1 2 3 7]
 [4 5 6 8]]


In [60]:
#insert 
x = np.array([1, 2, 3, 4])
print(x)

x = np.insert(x, 1, 5)
print(x)

x = np.insert(x, 2, [7, 8])
print(x)

x = np.insert(x, 3, [9, 10])
print(x)


[1 2 3 4]
[1 5 2 3 4]
[1 5 7 8 2 3 4]
[ 1  5  7  9 10  8  2  3  4]


In [61]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print("******************")
x = np.insert(x, 1, [7, 8, 9], axis=0)
print(x)
print("******************")
x = np.insert(x, 1, [10, 11, 12], axis=1)
print(x)

[[1 2 3]
 [4 5 6]]
******************
[[1 2 3]
 [7 8 9]
 [4 5 6]]
******************
[[ 1 10  2  3]
 [ 7 11  8  9]
 [ 4 12  5  6]]


In [62]:
#column_stack
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print("******************")

#vstack
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.vstack((x, y))
print(z)
print("******************")

#hstack
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.hstack((x, y))
print(z)
print("******************")

#dstack
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.dstack((x, y))
print(z)



[[1 2 3]
 [4 5 6]]
******************
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
******************
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
******************
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


## Numpy Arrays VS Python Arrays performance

In [63]:
x = np.random.random(100000000)
x

array([0.95476352, 0.68375403, 0.51006334, ..., 0.82205966, 0.99924347,
       0.75081953])

In [72]:
start = time.time()
mean = sum(x) / len(x)
end = time.time()
print("mean: ", mean.round(2))
print("Time: ", end - start)

mean:  0.5
Time:  3.291491746902466


In [73]:
# numpy
start = time.time()
mean = np.mean(x)
end = time.time()
print("mean: ", mean.round(2))
print("Time: ", end - start)

mean:  0.5
Time:  0.029354095458984375
