In [7]:
import numpy as np

In [8]:
x = np.array([1, 2, 3, 4])
print(x[0])
print(x[3])
print(x[-1])
print(x[-2])

1
4
4
3


In [9]:
x[0] = 30
x[-1] = 60
print(x)

[30  2  3 60]


In [14]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x)
print(x[0, 1])

x[0, 1] = 20
print(x)
print(x[0, 1])

[[1 2 3 4]
 [5 6 7 8]]
2
[[ 1 20  3  4]
 [ 5  6  7  8]]
20


In [16]:
#delete 
x = np.array([1, 2, 3, 4])
print(x)

x = np.delete(x, [0, 1])
print(x)

x = np.delete(x, 0)
print(x)

[1 2 3 4]
[3 4]
[4]
