In [51]:
import numpy as np
import time

## Numpy Arrays (narrays)

In [52]:
x = np.array([1, 2, 3, 4])
print(x[0])
print(x[3])
print(x[-1])
print(x[-2])

1
4
4
3


In [53]:
x[0] = 30
x[-1] = 60
print(x)

[30  2  3 60]


In [54]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x)
print(x[0, 1])

x[0, 1] = 20
print(x)
print(x[0, 1])

[[1 2 3 4]
 [5 6 7 8]]
2
[[ 1 20  3  4]
 [ 5  6  7  8]]
20


In [55]:
#delete 
x = np.array([1, 2, 3, 4])
print(x)

x = np.delete(x, [0, 1])
print(x)

x = np.delete(x, 0)
print(x)

[1 2 3 4]
[3 4]
[4]


In [56]:
#axis = 0 = row
#axis = 1 = column

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x)
print("******************")
#delete row
x = np.delete(x, 0, axis=0)
print(x)
print("******************")
#delete column
x = np.delete(x, 0, axis=1)
print(x)

# x = np.delete(x, [0, 1], axis=0)
# print(x)

# x = np.delete(x, [0, 1], axis=1)
# print(x)

[[1 2 3 4]
 [5 6 7 8]]
******************
[[5 6 7 8]]
******************
[[6 7 8]]


In [57]:
#append
x = np.array([1, 2, 3, 4])
print(x)

x = np.append(x, [5, 6])
print(x)

x = np.append(x, [7, 8])
print(x)

[1 2 3 4]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]


In [58]:
#axis = 0 = row
#axis = 1 = column
x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.append(x, [[7, 8, 9]], axis=0)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
#axis = 0 = row
#axis = 1 = column
x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.append(x, [[7], [8]], axis=1)
print(x)

[[1 2 3 7]
 [4 5 6 8]]


In [60]:
#insert 
x = np.array([1, 2, 3, 4])
print(x)

x = np.insert(x, 1, 5)
print(x)

x = np.insert(x, 2, [7, 8])
print(x)

x = np.insert(x, 3, [9, 10])
print(x)


[1 2 3 4]
[1 5 2 3 4]
[1 5 7 8 2 3 4]
[ 1  5  7  9 10  8  2  3  4]


In [61]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print("******************")
x = np.insert(x, 1, [7, 8, 9], axis=0)
print(x)
print("******************")
x = np.insert(x, 1, [10, 11, 12], axis=1)
print(x)

[[1 2 3]
 [4 5 6]]
******************
[[1 2 3]
 [7 8 9]
 [4 5 6]]
******************
[[ 1 10  2  3]
 [ 7 11  8  9]
 [ 4 12  5  6]]


In [62]:
#column_stack
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print("******************")

#vstack
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.vstack((x, y))
print(z)
print("******************")

#hstack
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.hstack((x, y))
print(z)
print("******************")

#dstack
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.dstack((x, y))
print(z)



[[1 2 3]
 [4 5 6]]
******************
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
******************
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
******************
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


## Numpy Arrays VS Python Arrays performance

In [63]:
x = np.random.random(100000000)
x

array([0.95476352, 0.68375403, 0.51006334, ..., 0.82205966, 0.99924347,
       0.75081953])

In [72]:
start = time.time()
mean = sum(x) / len(x)
end = time.time()
print("mean: ", mean.round(2))
print("Time: ", end - start)

mean:  0.5
Time:  3.291491746902466


In [73]:
# numpy
start = time.time()
mean = np.mean(x)
end = time.time()
print("mean: ", mean.round(2))
print("Time: ", end - start)

mean:  0.5
Time:  0.029354095458984375


## Multi dimensional arrays cwith numpy

In [74]:
x = np.array([4, 5, 6, 7])
x

array([4, 5, 6, 7])

In [ ]:
#shape
print(x.shape)

#type 
print(type(x))

#dtype
print(x.dtype)

(4,)
<class 'numpy.ndarray'>
int64


In [83]:
x = np.array(['Hello', 'There'])
#shape
print(x.shape)

#type 
print(type(x))

#dtype
print(x.dtype)

(2,)
<class 'numpy.ndarray'>
<U5


In [86]:
y = np.array([2, 4, 5, 'Hello'])
y

array(['2', '4', '5', 'Hello'], dtype='<U21')

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)
print(x.dtype)
print(type(x))

[[1 2 3]
 [4 5 6]]
(2, 3)
int64
<class 'numpy.ndarray'>


In [89]:
# Force to be an integer with dtype

x = np.array([[1, 2, 3.5], [4, 5, 6]], dtype=np.int64)
print(x)
print(x.shape)
print(x.dtype)
print(type(x))

[[1 2 3]
 [4 5 6]]
(2, 3)
int64
<class 'numpy.ndarray'>


## Numpy Function

In [ ]:
# zeros

x = np.zeros((3, 4))
print(x)
print(x.shape)
print(x.dtype)
print(type(x))
print("******************")

x = np.zeros((3, 4), dtype=np.int64)
print(x)
print(x.shape)
print(x.dtype)
print(type(x))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
float64
<class 'numpy.ndarray'>
******************
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)
int64
<class 'numpy.ndarray'>


In [95]:
# ones 

x = np.ones((3, 4))
print(x)
print(x.shape)
print(x.dtype)
print(type(x))
print("******************")

x = np.ones((3, 4), dtype=np.int64)
print(x)
print(x.shape)
print(x.dtype)
print(type(x))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
float64
<class 'numpy.ndarray'>
******************
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(3, 4)
int64
<class 'numpy.ndarray'>


In [96]:
x = np.full((3, 4), 7)
print(x)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [98]:
#eye 
x = np.eye(3)
print(x)
print("******************")

x = np.eye(3, 4)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
******************
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [103]:
#dialog 
x = np.diag([1, 2, 3])
print(x)
print("******************")

x = np.diag([1, 2, 3], k=0)
print(x)
print("******************")

x = np.diag([1, 2, 3], k=1)
print(x)
print("******************")

x = np.diag([1, 2, 3, 4], k=-1)
print(x)
print("******************")

x = np.diag([1, 2, 3, 4], k=2)
print(x)
print("******************")


[[1 0 0]
 [0 2 0]
 [0 0 3]]
******************
[[1 0 0]
 [0 2 0]
 [0 0 3]]
******************
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]
******************
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
******************
[[0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 4]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
******************


In [104]:
#arrange
x = np.arange(10)
print(x)
print("******************")

x = np.arange(1, 10)
print(x)
print("******************")

x = np.arange(1, 10, 2)
print(x)
print("******************")

x = np.arange(1, 10, 2, dtype=np.int64)
print(x)
print("******************")

x = np.arange(1, 10, 2, dtype=np.float64)
print(x)
print("******************")

x = np.arange(1, 10, 2, dtype=np.complex128)

[0 1 2 3 4 5 6 7 8 9]
******************
[1 2 3 4 5 6 7 8 9]
******************
[1 3 5 7 9]
******************
[1 3 5 7 9]
******************
[1. 3. 5. 7. 9.]
******************


In [106]:
#linspace
x = np.linspace(0, 10, 5)
print(x)
print("******************")

x = np.linspace(0, 10, 5, dtype=np.int64)
print(x)
print("******************")

x = np.linspace(0, 10, 5, dtype=np.float64)
print(x)
print("******************")

x = np.linspace(0, 10, 5, dtype=np.complex128)
print(x)
print("******************")

x = np.linspace(0, 10, 5, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10. ]
******************
[ 0  2  5  7 10]
******************
[ 0.   2.5  5.   7.5 10. ]
******************
[ 0. +0.j  2.5+0.j  5. +0.j  7.5+0.j 10. +0.j]
******************
[0. 2. 4. 6. 8.]


In [114]:
# random

x = np.random.random((3, 4))
print(x)
print("******************")

x = np.random.rand(3, 4)
print(x)
print("******************")

x = np.random.rand(3, 4, 5)
print(x)
print("******************")




[[0.14566172 0.45979764 0.60490423 0.60442619]
 [0.69759311 0.68110324 0.13730662 0.73285113]
 [0.15484532 0.64036804 0.73383748 0.76428698]]
******************
[[0.17440145 0.01877628 0.46028254 0.5699427 ]
 [0.39506217 0.67788768 0.80634132 0.17901238]
 [0.09324627 0.25639078 0.92965984 0.8043229 ]]
******************
[[[0.5060782  0.50686755 0.19994178 0.24544607 0.84581651]
  [0.24937968 0.66426497 0.7593272  0.17342149 0.82284093]
  [0.2025301  0.2567739  0.4480961  0.30159802 0.43850985]
  [0.22055923 0.29599691 0.44361647 0.22518783 0.6672893 ]]

 [[0.76740139 0.10202354 0.55694894 0.97832872 0.85438398]
  [0.60427944 0.45239904 0.36520956 0.17364138 0.04082092]
  [0.46116389 0.0297012  0.44030201 0.3751076  0.61864829]
  [0.97371995 0.38602033 0.02951094 0.88040587 0.92743492]]

 [[0.54241191 0.42699062 0.84281018 0.14551192 0.89299846]
  [0.79073792 0.10389921 0.47799267 0.78756681 0.30996928]
  [0.8768267  0.08922897 0.81863992 0.72112108 0.61158134]
  [0.64554373 0.39674944 

In [111]:
#random.randint
x = np.random.randint(1, 10)
print(x)
print("******************")

x = np.random.randint(1, 10, 5)
print(x)
print("******************")

x = np.random.randint(1, 10, (3, 4))
print(x)
print("******************")

x = np.random.randint(1, 10, (3, 4, 5))
print(x)
print("******************")


5
******************
[9 5 1 9 2]
******************
[[6 2 4 5]
 [1 6 5 5]
 [4 9 9 1]]
******************
[[[9 8 9 9 7]
  [6 9 1 5 8]
  [6 3 5 7 1]
  [6 4 1 9 1]]

 [[9 9 5 2 7]
  [4 4 2 9 2]
  [5 3 1 5 6]
  [3 2 3 6 6]]

 [[8 6 9 5 7]
  [7 9 5 1 2]
  [4 8 6 4 9]
  [1 5 3 4 4]]]
******************


In [119]:
#reshape
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print("******************")
y = x.reshape(3, 2)
print(y)




[[1 2 3]
 [4 5 6]]
******************
[[1 2]
 [3 4]
 [5 6]]


## Slicing