In [3]:
import numpy as np
import time

## Numpy Arrays (narrays)

In [4]:
x = np.array([1, 2, 3, 4])
print(x[0])
print(x[3])
print(x[-1])
print(x[-2])

1
4
4
3


In [5]:
x[0] = 30
x[-1] = 60
print(x)

[30  2  3 60]


In [6]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x)
print(x[0, 1])

x[0, 1] = 20
print(x)
print(x[0, 1])

[[1 2 3 4]
 [5 6 7 8]]
2
[[ 1 20  3  4]
 [ 5  6  7  8]]
20


In [7]:
#delete 
x = np.array([1, 2, 3, 4])
print(x)

x = np.delete(x, [0, 1])
print(x)

x = np.delete(x, 0)
print(x)

[1 2 3 4]
[3 4]
[4]


In [8]:
#axis = 0 = row
#axis = 1 = column

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x)
print("******************")
#delete row
x = np.delete(x, 0, axis=0)
print(x)
print("******************")
#delete column
x = np.delete(x, 0, axis=1)
print(x)

# x = np.delete(x, [0, 1], axis=0)
# print(x)

# x = np.delete(x, [0, 1], axis=1)
# print(x)

[[1 2 3 4]
 [5 6 7 8]]
******************
[[5 6 7 8]]
******************
[[6 7 8]]


In [9]:
#append
x = np.array([1, 2, 3, 4])
print(x)

x = np.append(x, [5, 6])
print(x)

x = np.append(x, [7, 8])
print(x)

[1 2 3 4]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]


In [10]:
#axis = 0 = row
#axis = 1 = column
x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.append(x, [[7, 8, 9]], axis=0)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#axis = 0 = row
#axis = 1 = column
x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.append(x, [[7], [8]], axis=1)
print(x)

[[1 2 3 7]
 [4 5 6 8]]


In [12]:
#insert 
x = np.array([1, 2, 3, 4])
print(x)

x = np.insert(x, 1, 5)
print(x)

x = np.insert(x, 2, [7, 8])
print(x)

x = np.insert(x, 3, [9, 10])
print(x)


[1 2 3 4]
[1 5 2 3 4]
[1 5 7 8 2 3 4]
[ 1  5  7  9 10  8  2  3  4]


In [13]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print("******************")
x = np.insert(x, 1, [7, 8, 9], axis=0)
print(x)
print("******************")
x = np.insert(x, 1, [10, 11, 12], axis=1)
print(x)

[[1 2 3]
 [4 5 6]]
******************
[[1 2 3]
 [7 8 9]
 [4 5 6]]
******************
[[ 1 10  2  3]
 [ 7 11  8  9]
 [ 4 12  5  6]]


In [14]:
#column_stack
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print("******************")

#vstack
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.vstack((x, y))
print(z)
print("******************")

#hstack
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.hstack((x, y))
print(z)
print("******************")

#dstack
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.dstack((x, y))
print(z)



[[1 2 3]
 [4 5 6]]
******************
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
******************
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
******************
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


## Numpy Arrays VS Python Arrays performance

In [15]:
x = np.random.random(100000000)
x

array([0.56687969, 0.52090624, 0.44398529, ..., 0.38908458, 0.73828924,
       0.41016378])

In [16]:
start = time.time()
mean = sum(x) / len(x)
end = time.time()
print("mean: ", mean.round(2))
print("Time: ", end - start)

mean:  0.5
Time:  3.9471869468688965


In [17]:
# numpy
start = time.time()
mean = np.mean(x)
end = time.time()
print("mean: ", mean.round(2))
print("Time: ", end - start)

mean:  0.5
Time:  0.02067875862121582


## Multi dimensional arrays cwith numpy

In [18]:
x = np.array([4, 5, 6, 7])
x

array([4, 5, 6, 7])

In [19]:
#shape
print(x.shape)

#type 
print(type(x))

#dtype
print(x.dtype)

(4,)
<class 'numpy.ndarray'>
int64


In [20]:
x = np.array(['Hello', 'There'])
#shape
print(x.shape)

#type 
print(type(x))

#dtype
print(x.dtype)

(2,)
<class 'numpy.ndarray'>
<U5


In [21]:
y = np.array([2, 4, 5, 'Hello'])
y

array(['2', '4', '5', 'Hello'], dtype='<U21')

In [22]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)
print(x.dtype)
print(type(x))

[[1 2 3]
 [4 5 6]]
(2, 3)
int64
<class 'numpy.ndarray'>


In [23]:
# Force to be an integer with dtype

x = np.array([[1, 2, 3.5], [4, 5, 6]], dtype=np.int64)
print(x)
print(x.shape)
print(x.dtype)
print(type(x))

[[1 2 3]
 [4 5 6]]
(2, 3)
int64
<class 'numpy.ndarray'>


## Numpy Function

In [24]:
# zeros

x = np.zeros((3, 4))
print(x)
print(x.shape)
print(x.dtype)
print(type(x))
print("******************")

x = np.zeros((3, 4), dtype=np.int64)
print(x)
print(x.shape)
print(x.dtype)
print(type(x))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
float64
<class 'numpy.ndarray'>
******************
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)
int64
<class 'numpy.ndarray'>


In [25]:
# ones 

x = np.ones((3, 4))
print(x)
print(x.shape)
print(x.dtype)
print(type(x))
print("******************")

x = np.ones((3, 4), dtype=np.int64)
print(x)
print(x.shape)
print(x.dtype)
print(type(x))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
float64
<class 'numpy.ndarray'>
******************
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(3, 4)
int64
<class 'numpy.ndarray'>


In [26]:
x = np.full((3, 4), 7)
print(x)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [27]:
#eye 
x = np.eye(3)
print(x)
print("******************")

x = np.eye(3, 4)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
******************
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [28]:
#dialog 
x = np.diag([1, 2, 3])
print(x)
print("******************")

x = np.diag([1, 2, 3], k=0)
print(x)
print("******************")

x = np.diag([1, 2, 3], k=1)
print(x)
print("******************")

x = np.diag([1, 2, 3, 4], k=-1)
print(x)
print("******************")

x = np.diag([1, 2, 3, 4], k=2)
print(x)
print("******************")


[[1 0 0]
 [0 2 0]
 [0 0 3]]
******************
[[1 0 0]
 [0 2 0]
 [0 0 3]]
******************
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]
******************
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
******************
[[0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 4]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
******************


In [29]:
#arrange
x = np.arange(10)
print(x)
print("******************")

x = np.arange(1, 10)
print(x)
print("******************")

x = np.arange(1, 10, 2)
print(x)
print("******************")

x = np.arange(1, 10, 2, dtype=np.int64)
print(x)
print("******************")

x = np.arange(1, 10, 2, dtype=np.float64)
print(x)
print("******************")

x = np.arange(1, 10, 2, dtype=np.complex128)

[0 1 2 3 4 5 6 7 8 9]
******************
[1 2 3 4 5 6 7 8 9]
******************
[1 3 5 7 9]
******************
[1 3 5 7 9]
******************
[1. 3. 5. 7. 9.]
******************


In [30]:
#linspace
x = np.linspace(0, 10, 5)
print(x)
print("******************")

x = np.linspace(0, 10, 5, dtype=np.int64)
print(x)
print("******************")

x = np.linspace(0, 10, 5, dtype=np.float64)
print(x)
print("******************")

x = np.linspace(0, 10, 5, dtype=np.complex128)
print(x)
print("******************")

x = np.linspace(0, 10, 5, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10. ]
******************
[ 0  2  5  7 10]
******************
[ 0.   2.5  5.   7.5 10. ]
******************
[ 0. +0.j  2.5+0.j  5. +0.j  7.5+0.j 10. +0.j]
******************
[0. 2. 4. 6. 8.]


In [31]:
# random

x = np.random.random((3, 4))
print(x)
print("******************")

x = np.random.rand(3, 4)
print(x)
print("******************")

x = np.random.rand(3, 4, 5)
print(x)
print("******************")




[[0.5971078  0.74713544 0.60316291 0.02462891]
 [0.25807253 0.81555613 0.71789374 0.86742603]
 [0.21850937 0.68989375 0.0972799  0.63829642]]
******************
[[0.85401214 0.02380468 0.03532195 0.52589139]
 [0.93072972 0.78699342 0.96769673 0.61585237]
 [0.11679021 0.11697884 0.4879144  0.40878818]]
******************
[[[0.71089247 0.30293956 0.6958503  0.64963234 0.64758267]
  [0.43312247 0.61700713 0.60543741 0.64014171 0.44508836]
  [0.76117097 0.54699281 0.46468055 0.96400616 0.22469976]
  [0.37410117 0.0484362  0.28205054 0.02890927 0.14395185]]

 [[0.59593626 0.64786134 0.60082587 0.89703932 0.79373144]
  [0.45272032 0.08571564 0.35906618 0.19832104 0.32804659]
  [0.32577462 0.28452537 0.72805451 0.00472306 0.08579553]
  [0.1703726  0.08730146 0.31857152 0.92741614 0.49131346]]

 [[0.9264692  0.70044113 0.53066885 0.20559371 0.41822452]
  [0.24293422 0.17245286 0.52609228 0.48493011 0.1305579 ]
  [0.10204678 0.33453938 0.33872511 0.73023505 0.51600699]
  [0.53759219 0.8571912  

In [32]:
#random.randint
x = np.random.randint(1, 10)
print(x)
print("******************")

x = np.random.randint(1, 10, 5)
print(x)
print("******************")

x = np.random.randint(1, 10, (3, 4))
print(x)
print("******************")

x = np.random.randint(1, 10, (3, 4, 5))
print(x)
print("******************")


8
******************
[9 2 8 1 6]
******************
[[9 1 8 5]
 [7 7 7 4]
 [5 1 5 2]]
******************
[[[6 3 8 3 1]
  [9 9 6 9 5]
  [4 6 1 4 9]
  [5 1 8 7 6]]

 [[1 6 1 8 7]
  [1 9 8 7 1]
  [5 4 9 8 7]
  [3 6 2 2 2]]

 [[5 4 5 3 6]
  [5 6 7 2 6]
  [9 8 6 2 1]
  [1 9 6 5 2]]]
******************


In [33]:
#reshape
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print("******************")
y = x.reshape(3, 2)
print(y)




[[1 2 3]
 [4 5 6]]
******************
[[1 2]
 [3 4]
 [5 6]]


## Slicing

In [34]:
x = np.arange(20).reshape(4, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [35]:
#rows
z = x[0:1]
print(z)
print("******************")

z = x[0:2]
print(z)
print("******************")

z = x[0:3]
print(z)
print("******************")

[[0 1 2 3 4]]
******************
[[0 1 2 3 4]
 [5 6 7 8 9]]
******************
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
******************


In [36]:
#columns
z = x[:, 0:1]
print(z)
print("******************")

#rows and columns

z = x[0:2, 0:2]
print(z)
print("******************")

z = x[0:2, 3:]
print(z)
print("******************")

#With arrays
z = x[0:2, [0, 2]]
print(z)
print("******************")

[[ 0]
 [ 5]
 [10]
 [15]]
******************
[[0 1]
 [5 6]]
******************
[[3 4]
 [8 9]]
******************
[[0 2]
 [5 7]]
******************


In [37]:
# By reference
z = x
print(x)
print('\n')
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [38]:
z[1,1] = 99
print(z)
print("******************")
print(x)

[[ 0  1  2  3  4]
 [ 5 99  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
******************
[[ 0  1  2  3  4]
 [ 5 99  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [39]:
x = np.arange(20).reshape(4, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [40]:
# Copy, not by reference
z = x[0:2, 3:].copy()
print(z)
z[1,1] = 99
print(z)
print("******************")
print(x)

[[3 4]
 [8 9]]
[[ 3  4]
 [ 8 99]]
******************
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## Boolean Index

In [41]:
x = np.arange(50).reshape(5, 10)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [42]:
y = x[x > 25]
print(y)

[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [43]:
print(x[ (x>25) & (x<30) ])

[26 27 28 29]


In [44]:
x[ (x>25) & (x<30) ] = 666
print(x)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25 666 666 666 666]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]]


In [50]:
x = np.random.randint(1, 25, size=(100))
print(x)

[17  6 10 17 22  8  4  9 24  1  9 14  4 16  2  6 11 23 21  3 21 19  5 24
  1 22  3 16  1 22 21 10 16 20  5 15 24  1  3 22  8 14 15  1  6 14 12  8
  7 17  2  5 21 12  3  9 19  5  8 10 15 17 17  8 14  7 20 13 10 19 22 24
 24 20 11 22  2 15 21  7  2  5 24 14 12 12 13  6 21 15 12 17 12  1 10 15
 19 16  6 19]


In [51]:
print(x[x==20])

[20 20 20]


## Arithmetic operations and broadcasting

In [52]:
x = np.arange(4)
y = np.arange(4, 8)
print(x)
print("******************")
print(y)

[0 1 2 3]
******************
[4 5 6 7]


In [57]:
x = np.arange(4).reshape(2, 2)
y = np.arange(4, 8).reshape(2, 2)
print(x)
print("******************")
print(y)

[[0 1]
 [2 3]]
******************
[[4 5]
 [6 7]]


In [58]:
print(x + y)
print("******************")
print(np.add(x, y))

[[ 4  6]
 [ 8 10]]
******************
[[ 4  6]
 [ 8 10]]


In [59]:
print(x - y)
print("******************")
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
******************
[[-4 -4]
 [-4 -4]]


In [60]:
print(x * y)
print("******************")
print(np.multiply(x, y))

[[ 0  5]
 [12 21]]
******************
[[ 0  5]
 [12 21]]


In [61]:
print(x / y)
print("******************")
print(np.divide(x, y))

[[0.         0.2       ]
 [0.33333333 0.42857143]]
******************
[[0.         0.2       ]
 [0.33333333 0.42857143]]


In [62]:
print(np.sqrt(x))

[[0.         1.        ]
 [1.41421356 1.73205081]]


In [63]:
print(np.exp(x))

[[ 1.          2.71828183]
 [ 7.3890561  20.08553692]]


In [64]:
print(np.power(x,2))

[[0 1]
 [4 9]]


In [68]:
#mean , std, median
print(x)
print("******************")
print(np.mean(x))
print(np.std(x))
print(np.median(x))

[[0 1]
 [2 3]]
******************
1.5
1.118033988749895
1.5


In [66]:
print(np.mean(x, axis=0))

[1. 2.]


In [69]:
print(np.max(x))
print(np.min(x))

3
0


## Broadcasting

In [71]:
x = np.arange(4).reshape(2, 2)
x

array([[0, 1],
       [2, 3]])

In [72]:
print(x+4)

[[4 5]
 [6 7]]


In [73]:
y = np.array([7, 8])
y

array([7, 8])

In [74]:
print(x+y)

[[ 7  9]
 [ 9 11]]
